_BASE_: config.yaml
MODEL:
  META_ARCHITECTURE: "Seg4DiffOVSS"
  WEIGHTS: None
  BACKBONE:
    FREEZE_AT: 0
    NAME: "SD3Backbone"
    NUM_TOKENS: 0
    FP16: True
    USE_LORA: False
    LORA_RANK: 16
    SEED: None
    SOFTMAX: True
    KEEP_HEAD: False
    ATTENTION_LAYERS: [9]
  SEM_SEG_HEAD:
    TRAIN_CLASS_JSON: "datasets/coco.json"
    TEST_CLASS_JSON: "datasets/voc21.json"
  NORM_BEFORE_MERGE: False
  NORM_AFTER_MERGE: False
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  GT_ONLY_PROMPT: True
  CLIP_FILTERING: False
  WITH_SOS_EOS: False
  NUM_INFERENCE_STEPS: 28
  NOISE_STEPS: 8
  OUTPUT_POWER: 1.0
  W: 0.3
  EVAL_MODE: None
SOLVER:
  AMP:
    ENABLED: False
  IMS_PER_BATCH: 4
  MAX_ITER: 80000
  BACKBONE_MULTIPLIER: 1.0