_BASE_: config.yaml
MODEL:
  EVAL_UNSUP: True
  META_ARCHITECTURE: "Seg4DiffUnsup"
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  MASK_LOSS_WEIGHT: 0.2
  DICE_LOSS_WEIGHT: 0.2
  KL_THRESHOLD: 0.035
  MAX_MASK: 32
  USE_ATTN_MLP: False
  SHORT_CAPTION: True
  CAPTION_DROPOUT: 0.
  FM_WEIGHT: 1.
  VISUALIZE_ATTENTION: False
  VISUALIZE_VAL_ATTENTION: False
  GENERATE_VAL_IMAGES: False
  OUTPUT_POWER: 1.0 
  NOISE_STEPS: 8
  BACKBONE:
    FREEZE_AT: 0
    NAME: "SD3Backbone"
    NUM_TOKENS: 154
    SEED: None
    FP16: True
    USE_LORA: False
    LORA_RANK: 16
    SOFTMAX: True
    KEEP_HEAD: False
    ATTENTION_LAYERS: [9]
  SEM_SEG_HEAD:
    TRAIN_CLASS_JSON: "datasets/coco.json"
    TEST_CLASS_JSON: "datasets/voc21.json"
DATASETS:
  TRAIN: ("coco_2017_train_stuff_all_sem_seg",)
  TEST: ("coco_2017_test_stuff_all_sem_seg",)
INPUT:
  STRONG_AUG: False
  CROP:
    ENABLED: False
    TYPE: "absolute"
    SIZE: (640, 640)
    SINGLE_CATEGORY_MAX_AREA: 1.0
  MIN_SIZE_TRAIN: (1024, )
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 640
  MAX_SIZE_TEST: 2560
  COLOR_AUG_SSD: False 
  SIZE_DIVISIBILITY: 640
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "mask_former_semantic"
TEST:
  EVAL_PERIOD: 100
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
SOLVER:
  IMS_PER_BATCH: 8
  GRADIENT_ACCUMULATION_STEPS: 1
  CHECKPOINT_PERIOD: 250
  BASE_LR: 0.0001
  MAX_ITER: 3000
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 500
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BACKBONE_MULTIPLIER: 0.1
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 0.01
    NORM_TYPE: 2.0
  AMP:
    ENABLED: True
VERSION: 2
CUDNN_BENCHMARK: True